### ISSUE TITLE
Weird Compiler issues: Parameter 'rDate' has no positive reference in body '#1'

### ISSUE THREAD

**Issue by tazzme** [ujhelyiz/EMF-IncQuery#387]
Hi,

I like your project very much as I have written my doctoral thesis in a close area in the late 2000. I am now working for a large company and I find EMFIncQuery could be very useful in our current project. I achieved creating and executing simple queries with the EMFQueryEngine, but now I'm struggeling with an issue, which could possibly be a bug in the compiler, similar to #77 

The following pattern produces a compiler error "Parameter 'rDate' is never referenced in body '#1'"

```
pattern deploymentOnMember(
				member : java ^iccm.model.EnvironmentMember,
 				ipv : java ^iccm.model.InstalledProductVersion,
				rDate : java ^java.util.Date) = {
	EnvironmentMember.installedProductVersions(member, ipv);
	InstalledProductVersion.deploymentDate(ipv, dDate);
	check(rDate > dDate);
	neg find moreRecentVersion(member, ipv, _ipv2);
}
```

If I add the following lines, I get the compiler error 'Parameter 'rDate' has no positive reference in body '#1''
```
	java ^java.util.Date(rDate);
	java ^java.util.Date(dDate);
```
What am I doing wrong?

Thank you.
Theresa

**Comment by ujhelyiz** [comment]
Hi,

thank you for your interest in EMF-IncQuery/VIATRA. We'll be glad if you believe, the project is useful for you.

Looking at the pattern definition, to me it seems the validator is correct in theory (but the error message is quite misleading here). The problem here is that the pattern matcher has to be able to enumerate all possible values for all parameters (which is clearly impossible for java Date values), while in the current case is impossible for the parameter rDate:
- The only thing we know about it that it is greater than some deploymentDate available in the model that is a practically infinite amount of Date values.
- Adding additional constraints as you have mentioned, does not help here. The `java ^java.util.Date(dDate);` line is irrelevant, as the deployment dates are enumerated based on information stored in the model; while `java ^java.util.Date(rDate);` does not help making the values of rDate enumerable.

In other words, you have to change your pattern to be expressible in EMF-IncQuery/VIATRA: basically, the value of rDate has to be _deterministically_ calculable from elements you find in the model. E.g. you can express rDate is 10 days later that the deploymentDate; or you can compare two date values stored in the model, but cannot express all dates that are after some date found in the model.

I hope this explanation was clear; if not feel free to ask for clarification.

---

In addition to answering your question, I have two points to clarify here:
1. Looking at the issue text it was not clear to me whether you are using EMF-IncQuery or VIATRA. You mention EMF-IncQuery explicitly, but your query example includes features only present in the latest VIATRA release. This February EMF-IncQuery was merged into VIATRA (see [corresponding blog post](https://viatra.net/news/2016/2/say-goodbye-to-emf-incquery-say-hello-to-viatra-query) for details). We are glad to help to various issues, but it would help us to clarify which version you are using.
2. VIATRA is an open source project at eclipse.org, and we manage [public forums](https://www.eclipse.org/forums/index.php?t=thread&frm_id=147) and [bug tracker](https://bugs.eclipse.org/bugs/) there ([list of open bugs](https://bugs.eclipse.org/bugs/buglist.cgi?bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&classification=Modeling&columnlist=assigned_to%2Cbug_status%2Cshort_desc%2Ctarget_milestone%2Cversion&list_id=15394596&order=target_milestone%2Cversion%2Cpriority%2Cbug_severity&product=Viatra), [enter new bug here](https://bugs.eclipse.org/bugs/enter_bug.cgi?product=VIATRA)). It would also help us if questions or bug reports are collected there.

Finally, I have opened a [new issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=507732) to make the error messages easier to understand (and possibly see whether there is some kind of issue with incorrect reporting as well).

**Comment by tazzme** [comment]
Fine, thank you for your fast response and the good explanation. I was not aware of the fact, that check-expressions must be deterministically calculable. So I solved this with rewriting the query. Thank you.
